name: Build and Package JAR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.11-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build, test and package
        run: ./mvnw clean verify package

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: target/*.jar

  sast:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.9.11-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python 3
        run: |
          apt-get update
          apt-get install -y python3 python3-venv python3-pip

      - name: Create and activate virtual environment, install Semgrep, run scan
        run: |
          python3 -m venv semgrep-venv
          # Используем точку вместо source
          . semgrep-venv/bin/activate
          pip install --upgrade pip
          pip install semgrep
          semgrep scan --config auto --sarif --output semgrep-sast-report.sarif
