name: Build, SAST & SCA

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.11-eclipse-temurin-21
    steps:
      - uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build, test and package
        run: ./mvnw clean verify package

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: target/*.jar

  sast:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install Python 3
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-venv python3-pip

      - name: Setup Semgrep and run scan
        run: |
          python3 -m venv semgrep-venv
          . semgrep-venv/bin/activate
          pip install --upgrade pip
          pip install semgrep
          semgrep scan --config auto --sarif --output semgrep-sast-report.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-sast-report.sarif

  sca:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.9.11-eclipse-temurin-21
    steps:
      - uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run OWASP Dependency-Check
        # Указываем полное имя плагина с версией
        run: ./mvnw org.owasp:dependency-check-maven:8.5.0:check

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
