name: Build and Package JAR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.11-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build, test and package
        run: ./mvnw clean verify package

      - name: Upload JAR artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifact
          path: target/*.jar

  sast:  # Из №3, если есть
    runs-on: ubuntu-latest
    needs: build
    container:
      image: maven:3.9.11-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: curl -sSfL https://raw.githubusercontent.com/semgrep/semgrep/develop/semgrep-install.sh | sh -s -- -b /usr/local/bin

      - name: Run Semgrep SAST
        run: semgrep scan --config auto --sarif --output semgrep-sast-report.sarif

      - name: Upload SARIF report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-sast-report.sarif

  sca:
    runs-on: ubuntu-latest
    needs: build   # После build
    container:
      image: maven:3.9.11-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run OWASP Dependency-Check
        run: ./mvnw dependency-check:check

      - name: Upload SCA report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html
